# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aqidata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(default=0)),
                ('humid', models.FloatField(default=0)),
                ('aqi01', models.FloatField(default=0)),
                ('aqi25', models.FloatField(default=0)),
                ('aqi10', models.FloatField(default=0)),
                ('voc', models.FloatField(default=0)),
                ('co2', models.FloatField(default=0)),
                ('log_date', models.DateTimeField(verbose_name='logging datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(verbose_name='created date')),
            ],
        ),
        migrations.AddField(
            model_name='aqidata',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logaqi.Room'),
        ),
    ]
